version: '3.8'

services:
  app:
    image: ${DOCKER_IMAGE_TS}
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["npm", "run", "dev"]
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'app_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: