services:
  app:
    image: ts-restful-api:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  k6:
    image: grafana/k6
    working_dir: /app
    environment:
      K6_WEB_DASHBOARD: true
    tty: true
    command: >
      run src/ping.js
    ports:
      - "5665:5665"
    volumes:
      - ./k6:/app

  mysql:
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'app_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: